version: 0.0
os: linux
files:
  - source: /myapp.jar
    destination: /opt/myapp
hooks:
  AfterInstall:
    - location: scripts/start_server.sh
      timeout: 5
      runas: root
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 10
      runas: root
