version: 0.0
os: linux
files:
  - source: /myapp.service
    destination: /etc/systemd/system
  - source: /conf/server/application-server.yml
    destination: /opt/myapp/conf
  - source: /myapp.jar
    destination: /opt/myapp
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 5
      runas: root
  AfterInstall:
    - location: scripts/start_server.sh
      timeout: 5
      runas: root
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 10
      runas: root
