version: 0.2
phases:
  build:
    commands:
      - mvn clean package -DskipTests -DskipITs
  post_build:
    commands:
      # move the jar (by wildcard, agnostic to its name) to top level app.jar
      - mv target/*.jar myapp.jar
artifacts:
  files:
    - myapp.jar
