Resources:
  CodebuildMyBuildProjectRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: codebuild-my-build-project-role
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: codebuild-my-build-project-role-2
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Resource:
                  - arn:aws:logs:eu-west-3:870103585828:log-group:/aws/codebuild/my-codebuild-project
                  - arn:aws:logs:eu-west-3:870103585828:log-group:/aws/codebuild/my-codebuild-project:*
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
              - Effect: Allow
                Resource:
                  - arn:aws:s3:::codepipeline-eu-west-3-*
                Action:
                  - s3:PutObject
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:GetBucketAcl
                  - s3:GetBucketLocation
              - Effect: Allow
                Action:
                  - codebuild:CreateReportGroup
                  - codebuild:CreateReport
                  - codebuild:UpdateReport
                  - codebuild:BatchPutTestCases
                  - codebuild:BatchPutCodeCoverages
                Resource:
                  - arn:aws:codebuild:eu-west-3:870103585828:report-group/my-codebuild-project-*
Outputs:
  CodebuildRole:
    Description: role pour codebuild lié au projet "kata-cloud2"
    Value: !Ref CodebuildMyBuildProjectRole
    Export:
      Name: CodebuildMyBuildProjectRole
